@urlDev = http://localhost:4000

### add product 
POST http://localhost:4000/products/add
Content-Type: application/json

{
    "product" : {
        "productId": 14,
        "code": "P14",
        "name": "Vans Old Skool",
        "brand": "Vans",
        "description": "Black ",
        "price": 50,
        "image": "https://bizweb.dktcdn.net/100/373/032/products/vans-old-skool-canvas-black-white.png?v=1601632272540",
        "specs": [
        {
            "k": "color",
            "v": "black/white"
        },
        {
            "k": "size",
            "v": "8US"
        }
    ],

    "category": "Sneaker",
    "inStock": "63f86da475d99f3b73a84d38"
    }
}

### get products 
GET http://localhost:4000/products/get
Content-Type: application/json

### get product by productId 
GET http://localhost:4000/products/get/14

### get brand products
GET http://localhost:4000/products/get/brand?q=Nike


### update product
PATCH  http://localhost:4000/products/update/1 
Content-Type: application/json

{
    "quantity" : 2,
    "specs" : [
        {
            "k" : "color",
            "v" : "red"
        },
        {
            "k" : "size",
            "v" : "8UK"
        },
        {
            "k" : "cond",
            "v" : "9/10"
        }
    ]
}


### add inventory 
POST http://localhost:4000/inventories/add
Content-Type: application/json

{
    "inventory": { 
        "productId": 78,
        "quantity": 6,
        "brand" : "Vans",
        "reservation": []
    }
}

### get inventory by id 
GET http://localhost:4000/inventories/get/1
Content-Type: application/json

### add to cart 
POST http://localhost:4000/carts/add
Content-Type: application/json

{
        "userId" : "404",
        "productId": 1, 
        "quantity": 5
}

### remove from cart
PATCH http://localhost:4000/carts/remove
Content-Type: application/json

{
    "userId": "007",
    "productId": 1
}

### get cart items
GET  http://localhost:4000/carts/get/404

### get cart items quantity by productId
GET  http://localhost:4000/carts/get-quantity/404

### create order
POST http://localhost:4000/orders/add
Content-Type: application/json  

{ 
        "userId" : "007",
        "fullName" : "Huynh Gia Lam",
        "email" : "gialamhuynh3004@gmail.com",
        "phoneNumber" : "0966440814",
        "address" : "2/39 Do Quang Co",
        "province" : "HCM",
        "district" : "Cu Chi",
        "ward" : "Thi tran Cu Chi"
    
}

### create order test 
POST http://localhost:4000/orders/add/test 
Content-Type: application/json

{
    "userId" : "404"
}


### get order 
GET  http://localhost:4000/orders/get/007
 

### REDIS set user 
POST {{urlDev}}/redis/user/
Content-Type: application/json

{
    "key" : "user-ily",
    "payload" : {
        "uid" : 1141,
        "name" : "puonguyen.com"
    } 
}

### REDIS get user 
GET {{urlDev}}/redis/user/u:304
Content-Type: application/json


### user insert many 
GET  {{urlDev}}/users/get/?page=2&pagesize=4

